zookeeper:
  image: samsara/zookeeper
  ports:
    - "2181:2181"
    - "15001:15000"
  environment:
    ZK_SERVER_ID: 1
  volumes:
    - ~/tmp/docker/zk1/logs:/logs
    - ~/tmp/docker/zk1/data:/data


kafka:
  image: samsara/kafka 
  ports:
    - "9092:9092"
    - "15002:15000"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_BROKER_ID: 1
  volumes:
    - ~/tmp/docker/kafka1/logs:/logs
    - ~/tmp/docker/kafka1/data:/data

