#####  A file of useful http requests for emacs restclient users

#################### Schema Registry calls #################### 

GET http://192.168.59.103:8081/subjects
Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json

#Register a new schema to be used for kafka values
POST http://192.168.59.103:8081/subjects/avro-messages-value/versions
Content-Type: application/vnd.schemaregistry.v1+json
Accept: application/vnd.schemaregistry.v1+json, application/vnd.schemaregistry+json, application/json

{
  "schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\":\"first_name\", \"type\":\"string\"},{\"name\":\"last_name\", \"type\":\"string\"}]}"
}



#################### Kafka Rest Proxy calls #################### 
# Get a list of topics
GET http://192.168.59.103:8082/topics

# Get info about one topic
GET http://192.168.59.103:8082/topics/_schemas

# Get info about one topic
GET http://192.168.59.103:8082/topics/avro-messages

# Post an avro message (Note - current kafka nodes are configure to auto create topics)
POST http://192.168.59.103:8082/topics/avro-messages
Content-Type: application/vnd.kafka.avro.v1+json
Accept: application/vnd.kafka.v1+json, application/vnd.kafka+json, application/json

{
  "value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\":\"first_name\", \"type\":\"string\"},{\"name\":\"last_name\", \"type\":\"string\"}]}",
  "records": [
  {
    "value": {"first_name":"Dayo", "last_name":"Oliyide"}
  },
  {
    "value": {"first_name":"Luke", "last_name":"Skywalker"},
    "partition": 1
  },
  {
    "value": {"first_name":"Obiwan", "last_name":"Kenobi"}
  }
 ]
}

